---
#
# Ansible managed
#
repository:
  description: Install and configure HashiCorp Vault Agent on your system.
  homepage: https://robertdebock.nl/
  topics: vaultagent, application, cloud, infrastructure, linux, security, system, tools, ansible, molecule, playbook
